-- CREATE TABLE CLIENTES
CREATE TABLE clientes (
    id INT PRIMARY KEY,
    nome VARCHAR(256) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    email VARCHAR(100) NOT NULL,
    data_nascimento DATE
);

-- CREATE SEQUENCE CLIENTES_ID_SEQ
CREATE SEQUENCE CLIENTES_ID_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE TABLE PRODUTOS
CREATE TABLE produtos (
    id INT PRIMARY KEY,
    nome VARCHAR(256) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    preco NUMERIC(10, 2) NOT NULL,
    ingredientes TEXT
);

-- CREATE SEQUENCE PRODUTOS_ID_SEQ
CREATE SEQUENCE PRODUTOS_ID_SEQ START WITH 1 INCREMENT BY 1;
