-- CREATE TABLE CLIENTES
CREATE TABLE clientes (
    id INT PRIMARY KEY,
    nome VARCHAR(256) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    email VARCHAR(100) NOT NULL,
    data_nascimento DATE
);

-- CREATE SEQUENCE CLIENTES_ID_SEQ
CREATE SEQUENCE CLIENTES_ID_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE TABLE PRODUTOS
CREATE TABLE produtos (
    id INT PRIMARY KEY,
    nome VARCHAR(256) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    preco NUMERIC(10, 2) NOT NULL,
    ingredientes TEXT
);

-- CREATE SEQUENCE PRODUTOS_ID_SEQ
CREATE SEQUENCE PRODUTOS_ID_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE TABLE PEDIDOS
CREATE TABLE pedidos (
    id INT PRIMARY KEY,
    cliente_id INT NOT NULL,
    valor NUMERIC(10, 2) NOT NULL,
    situacao INT NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
);

-- CREATE SEQUENCE PEDIDOS_ID_SEQ
CREATE SEQUENCE PEDIDOS_ID_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE TABLE RELACIONAMENTO PEDIDO E PRODUTO
CREATE TABLE pedido_produto (
    pedido_id INT NOT NULL,
    produto_id INT NOT NULL,
	quantidade INT NOT NULL,
    PRIMARY KEY (pedido_id, produto_id),
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE,
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE
);
