CREATE TABLE TB_CLI_CLIENTE (
    CLI_ID INT PRIMARY KEY,
    CLI_NM_NOME VARCHAR(256) NOT NULL,
    CLI_NM_CPF VARCHAR(14) NOT NULL,
    CLI_NM_EMAIL VARCHAR(100) NOT NULL,
    CLI_DH_NASCIMENTO DATE
);

CREATE SEQUENCE SQ_CLI_CLIENTE START WITH 1 INCREMENT BY 1;
