CREATE TABLE TB_PRO_PRODUTO (
    PRO_ID INT PRIMARY KEY,
    PRO_NM_NOME VARCHAR(256) NOT NULL,
    PRO_TP_CATEGORIA INT NOT NULL,
    PRO_VL_PRODUTO NUMERIC(10, 2) NOT NULL
);

CREATE SEQUENCE SQ_PRO_PRODUTO START WITH 1 INCREMENT BY 1;
