CREATE TABLE TB_PAG_PAGAMENTO (
    PAG_ID INT PRIMARY KEY,
    PAG_ST_PAGAMENTO INT NOT NULL,
    PAG_TP_PAGAMENTO INT NOT NULL,
    PAG_VL_COMPRA NUMERIC(10, 2) NOT NULL,
    PAG_DH_PAGAMENTO TIMESTAMP WITHOUT TIME ZONE
);

CREATE SEQUENCE SQ_PAG_PAGAMENTO START WITH 1 INCREMENT BY 1;
