CREATE TABLE TB_PED_PEDIDO (
    PED_ID INT PRIMARY KEY,
    CLI_ID INT NOT NULL,
    PAG_ID INT,
    PED_ST_PEDIDO INT NOT NULL,
    PED_NM_PROTOCOLO VARCHAR(50) NOT NULL UNIQUE,
    PED_DH_PEDIDO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PED_DH_ATUALIZACAO_PEDIDO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (CLI_ID) REFERENCES TB_CLI_CLIENTE(CLI_ID) ON DELETE CASCADE,
    FOREIGN KEY (PAG_ID) REFERENCES TB_PAG_PAGAMENTO(PAG_ID) ON DELETE CASCADE
);

CREATE SEQUENCE SQ_PED_PEDIDO START WITH 1 INCREMENT BY 1;
