CREATE TABLE REL_PED_PRO (
    PED_ID INT NOT NULL,
    PRO_ID INT NOT NULL,
    PED_QT_PEDIDO INT NOT NULL,
    PRIMARY KEY (PED_ID, PRO_ID),
    FOREIGN KEY (PED_ID) REFERENCES TB_PED_PEDIDO(PED_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRO_ID) REFERENCES TB_PRO_PRODUTO(PRO_ID) ON DELETE CASCADE
);
