services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  srv_monolito:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db

  mercadopagofake:
    image: tgobmdev/mercadopago_fake:v1
    container_name: mercadopago_fake_container
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
