services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  srv_cliente:
    build:
      context: .
      dockerfile: Dockerfile
      target: srv_cliente_builder
    env_file:
      - .env
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - db

  srv_produto:
    build:
      context: .
      dockerfile: Dockerfile
      target: srv_produto_builder
    env_file:
      - .env
    ports:
      - "8082:8080"
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge
