services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  srv_monolito:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db

  srv_wiremock:
    image: wiremock/wiremock:3.10.0
    container_name: wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
