apiVersion: apps/v1
kind: Deployment
metadata:
  name: mercadopagofake-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mercadopagofake
  template:
    metadata:
      labels:
        app: mercadopagofake
    spec:
      containers:
      - name: mercadopagofake-container
        image: tgobmdev/mercadopago_fake:v1
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
        ports:
          - containerPort: 8081
        env:
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: mercadopagofake-config
                key: SERVER_PORT
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          periodSeconds: 30
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          periodSeconds: 30
          initialDelaySeconds: 30
