services:
  parent:
    build:
      context: ../.
      dockerfile: Dockerfile
    image: parent:0.0.1
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: srv-produto:0.0.1
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
      - parent

networks:
  app-network:
    driver: bridge