apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-role
  labels:
    k8s-app: metrics-server
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
