name: pipeline-deploy
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      uses: actions/checkout@v2
        - name: Docker Login
          uses: docker/login-action@v3.3.0
          with:
            username: '${{secrets.DOCKERHUB_USER}}'
            password: '${{secrets.DOCKERHUB_TOKEN}}'
        - name: Build and push Docker images
          uses: docker/build-push-action@v6.15.0
          with:
            tags: 'gabriellmb05/tech-challenge:latest'
            context: .
            push: true

